[tests.yml]: Install Cython and Numpy Before MDAnalysis
MDAnalysis `<3.0` requires Cython `<3.0` for compilation (see
https://github.com/MDAnalysis/mdanalysis/pull/4129 and
https://github.com/cython/cython/issues/3690).  Otherwise, installing
MDAnalysis via pip throws the following error:

``` shell
Error compiling Cython file:
------------------------------------------------------------
...
    array_wrapper = ArrayWrapper()
    array_wrapper.set_data(<void*> data_ptr, <int*> &dim[0], dim.size, data_type)

    cdef np.ndarray ndarray = np.array(array_wrapper, copy=False)
    # Assign our object to the 'base' of the ndarray object
    ndarray.base = <PyObject*> array_wrapper
           ^
------------------------------------------------------------

MDAnalysis/lib/formats/cython_util.pyx:115:11: Assignment to a read-only property

Traceback (most recent call last):
  File "/home/runner/.local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
    main()
  File "/home/runner/.local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/home/runner/.local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
    return hook(config_settings)
  File "/tmp/pip-build-env-uemocs7v/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=['wheel'])
  File "/tmp/pip-build-env-uemocs7v/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
    self.run_setup()
  File "/tmp/pip-build-env-uemocs7v/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 488, in run_setup
    self).run_setup(setup_script=setup_script)
  File "/tmp/pip-build-env-uemocs7v/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 338, in run_setup
    exec(code, locals())
  File "<string>", line 590, in <module>
  File "<string>", line 453, in extensions
  File "/tmp/pip-build-env-uemocs7v/overlay/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 1134, in cythonize
    cythonize_one(*args)
  File "/tmp/pip-build-env-uemocs7v/overlay/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: MDAnalysis/lib/formats/cython_util.pyx
```

Furthermore, MDAnalysis requires at leas NumPy `>=1.16.0`, but better
Numpy `>=1.19.2` (see
https://github.com/MDAnalysis/mdanalysis/issues/3374#issuecomment-889189979),
for setup:

``` shell
*** package "numpy" not found ***
MDAnalysis requires a version of NumPy (>=1.16.0), even for setup.
Please get it from http://numpy.scipy.org/ or install it through your package manager.
```